---
- name: Create local superuser account with SSH key and enforce cert login
  hosts: ##HOSTS##
  become: yes

  vars_prompt:
    - name: username
      prompt: "Enter the username"
      private: no
    - name: password1
      prompt: "Enter the first half of the password"
      private: yes
    - name: password2
      prompt: "Enter the second half of the password"
      private: yes

  tasks:
    - name: Combine password halves
      set_fact:
        combined_password: "{{ password1 }}{{ password2 }}"

    - name: Create the user
      user:
        name: "{{ username }}"
        password: "{{ combined_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    - name: Create .ssh directory if it doesn't exist
      become_user: "{{ username }}"
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"

    - name: Copy public SSH key to authorized_keys
      become_user: "{{ username }}"
      copy:
        src: "##SSH KEY PATH##"
        dest: "~/.ssh/authorized_keys"
        mode: "0600"
      ignore_errors: true

    - name: Set sshd_config to PasswordAuthentication no
      become: yes
      blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{username}}"
        block: |
           Match User "{{ username}}"
              PasswordAuthentication no

    - name: Grant sudo privileges to the user
      become_user: root
      command: usermod -aG sudo "{{ username }}"

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

    - name: Print results
      debug:
        msg: "Superuser '{{ username }}' has been created and can only log in via SSH cert!"
