---
- name: Create local breakglass user account with sudo privileges
  hosts: ##HOSTS##
  become: yes

  vars_prompt:
    - name: username
      prompt: "Enter the username"
      private: no
    - name: admin1_password
      prompt: "Enter the first half of the password"
      private: yes
    - name: admin2_password
      prompt: "Enter the second half of the password"
      private: yes

  tasks:
    - name: Combine password halves
      set_fact:
        combined_password: "{{ admin1_password }}{{ admin2_password }}"

    - name: Create the user
      user:
        name: "{{ username }}"
        password: "{{ combined_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    - name: Grant sudo privileges to the user
      become: yes
      become_user: root
      command: usermod -aG sudo "{{ username }}"

    - name: Print results
      debug:
        msg: "Superuser '{{ username }}' has been created!"
